baseURL: "https://splusq.github.io/"
languageCode: "en-us"
title: "Salman Quazi"
theme: 
  - hyde
params:
  description: "Engineering Manager for Microsoft Azure Speech in Silicon Valley, CA."
  themeColor: "theme-base-08"
permalinks:
  blog: /blog/:title/:year/:month
Menus:
  main:
    - Name: "Github"
      URL: "https://github.com/splusq/"
    - Name: "LinkedIn"
      URL: "https://www.linkedin.com/in/salmanquazi/"
    - Name: "Twitter"
      URL: "https://www.twitter.com/splusq"