baseURL: https://www.salmanq.com/
languageCode: en-us
title: Salman Quazi
theme: hugo-blog-awesome
enableEmoji: true
googleAnalytics: G-K4WVH5P91F
markup:
  highlight:
    noClasses: false
menu:
  main:
    - pageRef: /
      name: Home
      url: /
      weight: 10
    - pageRef: blog
      name: Blog
      url: /blog/
      weight: 20
params:
  sitename: Salman Quazi
  defaultColor: dark
  author:
    avatar: "img/avatar.jpg"
    intro: Salman Quazi
    name: Salman Quazi
    description: >-
      Director of Engineering for Microsoft Azure AI in Mountain View, CA.
  socialIcons:
    - name: github
      url: 'https://github.com/splusq'
    - name: twitter
      url: 'https://www.twitter.com/splusq'
    - name: linkedin
      url: 'https://www.linkedin.com/in/salmanquazi/'
    - name: Rss
      url: index.xml