baseURL: "https://www.salmanq.com/"
languageCode: "en-us"
theme: 
  - hello-friend
Copyright:
  Opinions are my own. | 2019 All Rights Reserved.
params:
  showReadingTime: true
  contentTypeName: blog
  defaultTheme: light
googleAnalytics: UA-38742121-1
languages:
  en:
    title: Salman Quazi
    subtitle: Blog
    params:
      Cover: hello
      logo:
        logoText: salmanq.com
    menu:
      main:
        - identifier: Posts
          name: Posts
          url: /blog
        - identifier: Github
          name: Github
          url: https://github.com/splusq/
        - identifier: LinkedIn
          name: LinkedIn
          url: https://www.linkedin.com/in/salmanquazi/
        - identifier: Twitter
          name: Twitter
          url: https://www.twitter.com/splusq
Menus:
  main:
    - Name: "Github"
      URL: "https://github.com/splusq/"
    - Name: "LinkedIn"
      URL: "https://www.linkedin.com/in/salmanquazi/"
    - Name: "Twitter"
      URL: "https://www.twitter.com/splusq"