baseURL: "https://www.salmanq.com/"
languageCode: "en-us"
title: "Salman Quazi"
theme:
  - papermod
params:
  defaultTheme: dark
  ShowReadingTime: true

googleAnalytics: UA-38742121-1
Menus:
  main:
    - Name: "Blog"
      URL: "/blog/"
    - Name: "Github"
      URL: "https://github.com/splusq/"
    - Name: "LinkedIn"
      URL: "https://www.linkedin.com/in/salmanquazi/"
    - Name: "Twitter"
      URL: "https://www.twitter.com/splusq"
