baseURL: "http://www.salmanq.com/"
languageCode: "en-us"
title: "Salman Quazi"
theme: 
  - hyde
params:
  description: "Engineering Manager for Microsoft Azure Speech in Silicon Valley, CA."
  themeColor: "theme-base-08"
googleAnalytics: UA-38742121-1
permalinks:
  blog: /:year/:month/:day/:title/
Menus:
  main:
    - Name: "About"
      URL: "/2014/08/resume.pdf"
    - Name: "Github"
      URL: "https://github.com/splusq/"
    - Name: "LinkedIn"
      URL: "https://www.linkedin.com/in/salmanquazi/"
    - Name: "Twitter"
      URL: "https://www.twitter.com/splusq"