baseURL: "https://www.salmanq.com/"
languageCode: "en-us"
title: "Salman Quazi"
theme: 
  - hyde
params:
  description: "Engineering Manager for Microsoft Azure Cognitive Services in Mountain View, CA."
  copyright: "Opinions are my own."
  themeColor: "theme-base-08"
Menus:
  main:
    - Name: "Blog"
      URL: "/blog/"    
    - Name: "Github"
      URL: "https://github.com/splusq/"
    - Name: "LinkedIn"
      URL: "https://www.linkedin.com/in/salmanquazi/"
    - Name: "Twitter"
      URL: "https://www.twitter.com/splusq"
